CREATE TABLE members
(
    `member_id`                 int NOT NULL AUTO_INCREMENT,
    `barcode_id`                varchar(12)  DEFAULT NULL,
    `last_name`                 varchar(50)  DEFAULT NULL,
    `first_name`                varchar(50)  DEFAULT NULL,
    `middle_name`               varchar(50)  DEFAULT NULL,
    `suffix`                    varchar(5)   DEFAULT NULL,
    `short_name`                varchar(50)  DEFAULT NULL,
    `member_address`            varchar(255) DEFAULT NULL,
    `home_phone`                varchar(50)  DEFAULT NULL,
    `work_phone`                varchar(50)  DEFAULT NULL,
    `cellular`                  varchar(50)  DEFAULT NULL,
    `email`                     varchar(50)  DEFAULT NULL,
    `date_of_birth`             datetime     DEFAULT NULL,
    `marital_status`            varchar(50)  DEFAULT NULL,
    `member_status`             varchar(20)  DEFAULT NULL,
    `gender`                    varchar(50)  DEFAULT NULL,
    `religion`                  varchar(50)  DEFAULT NULL,
    `education_level`           varchar(50)  DEFAULT NULL,
    `degree`                    varchar(50)  DEFAULT NULL,
    `illness`                   varchar(50)  DEFAULT NULL,
    `physical_limitations`      varchar(150) DEFAULT NULL,
    `dietary_requirements`      varchar(150) DEFAULT NULL,
    `dietary_requirements_desc` varchar(200) DEFAULT NULL,
    `contact_id`                int          DEFAULT NULL,
    `sponsor_id`                int          DEFAULT NULL,
    `chapter_id`                int          DEFAULT NULL,
    `parish_id`                 int          DEFAULT NULL,
    `date_adorer`               datetime     DEFAULT NULL,
    `date_hirang`               datetime     DEFAULT NULL,
    `date_council`              datetime     DEFAULT NULL,
    `is_active`                 boolean      DEFAULT TRUE,
    `date_created`              timestamp    DEFAULT CURRENT_TIMESTAMP,
    `date_updated`              timestamp ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (member_id),
    FOREIGN KEY (contact_id) REFERENCES members (member_id),
    FOREIGN KEY (sponsor_id) REFERENCES members (member_id),
    FOREIGN KEY (chapter_id) REFERENCES chapter_info (chapter_id),
    FOREIGN KEY (parish_id) REFERENCES parish (parish_id)
);